
name: CI-CD Pipeline to AWS Elastic Beanstalk
env : 
   EB_PACKAGE_S3_BUCKE_NAME : "adv-it-flackapp"
   EB_APPLICATION_NAME      : "MyFlack"
   EB_ENVIRONMENT_NAME      : "MyFlack-env"
   DEPLOY_PACKAGE_NAME      : "flack_app_${{ github.sha }}.zip"
   AWS_REGION_NAME          : "us-east-1"
   
on:
  push:
    branches: 
           main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure my AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
         aws-access-key-id : ${{ secrets.MY_AWS_ACCESS_KEY }}
         aws-secret-key-id : ${{ secrets.MY_AWS_SECRET_KEY }}
         aws-region        : ${{ env.AWS_REGION_NAME }}
         
      - name: Copy Deployment package to S3 backet
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKE_NAME }}/
   
      - name: Print Happy Massage for CI finish
        run : echo "CI pipeline part finished successfully"
