# This is a basic workflow to help you get started with Actions

#--------------------------------------------------------------
# GitHub Actions Part 1
#

name: My-Github-Actions-1
env:
  APPLICATION_NAME    : "Myflack"
  DEPLOY_PACKAGE_NAME : "flack-deploy-ver-${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  my_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps: 
    - name : Print Hello message in Testing
      run  : echo "Hello World from Testing job"   
      
    - name : Execute a few commands
      run  : |
             echo "Hello message 1"
             echo "Hello message 2"
             echo "Application name: ${{ env.APPLICATION_NAME }}"
             
    - name : List current folder
      run  : ls -la
      
    - name : Git Clone my Repo
      uses : actions/checkout@v1
      
    - name : List current folder
      run  : ls -la       
          
  my_deploy: 
    runs-on: ubuntu-latest 
    needs: [my_testing]
     
    steps: 
    - name : Print Hello message in Deploy
      run  : echo "Hello World from Deploy job"
       
    - name : Printing Deployment Ppackage
      run  : |
             echo "Deploy package name: ${{ env.DEPLOY_PACKAGE_NAME }}"
     
    - name : Test packages 1
      run  : aws --version
      
    - name : Test packages 2
      run  : zip
             
